CREATE TABLE IF NOT EXISTS pm_activity_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_id CHAR(64) NOT NULL COMMENT 'sha256(user_wallet + canonical_raw_json)',
  user_wallet VARCHAR(64) NOT NULL,
  proxy_wallet VARCHAR(64) NOT NULL DEFAULT '',
  timestamp_ms BIGINT NOT NULL DEFAULT 0,
  event_time DATETIME(3) NULL,
  condition_id VARCHAR(128) NOT NULL DEFAULT '',
  activity_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TRADE/REDEEM/MERGE...',
  size DECIMAL(38,18) NULL,
  usdc_size DECIMAL(38,18) NULL,
  transaction_hash VARCHAR(128) NOT NULL DEFAULT '',
  price DECIMAL(38,18) NULL,
  asset VARCHAR(128) NOT NULL DEFAULT '',
  side VARCHAR(16) NOT NULL DEFAULT '' COMMENT 'buy/sell',
  outcome_index INT NULL,
  title VARCHAR(1024) NOT NULL DEFAULT '',
  slug VARCHAR(255) NOT NULL DEFAULT '',
  market_tag VARCHAR(24) NOT NULL DEFAULT '' COMMENT 'btc/eth/sol/other',
  event_slug VARCHAR(255) NOT NULL DEFAULT '',
  outcome VARCHAR(128) NOT NULL DEFAULT '',
  source_offset INT NOT NULL DEFAULT 0,
  source_index INT NOT NULL DEFAULT 0,
  pulled_at DATETIME(3) NOT NULL,
  raw_json JSON NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_event_id (event_id),
  KEY idx_user_ts (user_wallet, timestamp_ms DESC),
  KEY idx_market_tag_ts (market_tag, timestamp_ms DESC),
  KEY idx_slug_ts (slug, timestamp_ms DESC),
  KEY idx_tx_hash (transaction_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
